[build-system]
# requires = [ "setuptools", "wheel", "pybind11>=2.10.0"]
requires = [ "setuptools >= 65.0.0", "pybind11>=2.10.0"]
build-backend = "setuptools.build_meta"

[project]
name = "yudet"
description = "A fast face detector."
keywords = ["face detection"]
version = "0.0.1"
authors = [
  { name="Wwupup", email="12032501@mail.sustech.edu.cn" },
]
readme = "README.md"
requires-python = ">=3.7"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: C++",
    "License :: OSI Approved :: BSD License",
    "Operating System :: POSIX :: Linux",
    "Classifier: Operating System :: Microsoft :: Windows",
    "Development Status :: 4 - Beta",
    "Topic :: Software Development",
    "Intended Audience :: Developers",
]

[project.urls]
"Homepage" = "https://github.com/Wwupup/libfacedetection.pypi"
"Bug Tracker" = "https://github.com/Wwupup/libfacedetection.pypi/issues"

# [tool.setuptools.packages.find]


